name: Generate Snake Animation



jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 gives Actions bot push access
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Aayush-0910
          outputs: |
            dist/snake.svg

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
